spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Hospital_appointment}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.generate-ddl=${SPRING_JPA_GENERATE_DDL:true}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

server.port=${SERVER_PORT:8080}